#配置log信息47.93.221.192
logging:
  config: classpath:log4j2.xml

server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.93.221.192:3306/bookstore?characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456
#阿里druid连接池驱动配置信息
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #初始化大小，最小，最大
      initial-size: 2
      min-idle: 2
      max-active: 10
  #连接池的配置信息
  #配置获取连接等待超时的时间
      maxWait: 6000
  #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
  #配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
  #配置文件上传大小
  servlet:
    multipart:
      max-file-size: 5MB